#!/bin/bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
utils_dir="$script_dir/utils"
function_dir="$script_dir/src"
export DATA_FILE="$script_dir/data/devices"

"$utils_dir/get_wol_cmd.sh"

cleanup() {
  unset DATA_FILE WOL_CMD
}

trap cleanup EXIT

# check for wakeonlan 
if [ -z "$WOL_CMD" ] || ! command -v "$WOL_CMD" &> /dev/null; then
    read -p "wakeonlan is not installed. Do you want to install it? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        if "$utils_dir/install_wol.sh"; then 
          echo"wakeonlan installed successfully"
        else 
          echo "Failed to install wakeonlan. Try to install manually"
          exit 1
        fi 
    else
        echo "wakeonlan is required for this script to function. Exiting."
        exit 1
    fi
fi

# make sure data file exists
if [ ! -f "$DATA_FILE" ]; then
    mkdir -p "$(dirname "$DATA_FILE")"
    touch "$DATA_FILE"
fi 

case "$1" in
    add|remove|up)
        if [ -f "$function_dir/$1.sh" ]; then
            func="$1"
            shift
            "$function_dir/$func.sh" "$@"
        else
            echo "Function not found: $1"
            exit 1
        fi
        ;;
    *)
        echo "Usage: netpower {add|remove|up} [arguments]"
        exit 1
        ;;
esac
